# SkylynxServerCompose for Prod
services:
  skylynx-express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skylynx-express
    env_file:
      - .env
    ports:
      - "5001:3200"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_BACKUP_HOST=${DB_BACKUP_HOST}
      - DB_BACKUP_PORT=${DB_BACKUP_PORT}
      - DB_BACKUP_USER=${DB_BACKUP_USER}
      - DB_BACKUP_PASSWORD=${DB_BACKUP_PASSWORD}
      - DB_BACKUP_NAME=${DB_BACKUP_NAME}
      - DB_BACKUP_PORTAL_NAME=${DB_BACKUP_PORTAL_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_JWT_SECRET=${SERVER_JWT_SECRET}
      - SKYLYNX_ADMIN_DIR=/app/admin
    volumes:
      - ./admin:/app/admin
    networks:
      - silverlining

  nginx:
    build:
      context: ./nginx
    container_name: skylynx-nginx
    ports:
      - "8080:80"
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - skylynx-express
    networks:
      - silverlining

networks:
  silverlining:
    external: true
