services:
  skylynx-express:
    stdin_open: true
    tty: true
    init: true
    image: skylynx-sever
    build:
      context: .                  
      dockerfile: Dockerfile.dev
    container_name: skylynx-express-dev
    env_file:
      - local.env
    ports:
      - "5001:3200"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_BACKUP_HOST=${DB_BACKUP_HOST}
      - DB_BACKUP_PORT=${DB_BACKUP_PORT}
      - DB_BACKUP_USER=${DB_BACKUP_USER}
      - DB_BACKUP_PASSWORD=${DB_BACKUP_PASSWORD}
      - DB_BACKUP_NAME=${DB_BACKUP_NAME}
      - DB_BACKUP_PORTAL_NAME=${DB_BACKUP_PORTAL_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_JWT_SECRET=${SERVER_JWT_SECRET}
      - SKYLYNX_ADMIN_DIR=/app/admin
    volumes:
      - .:/app
      - ./admin:/app/admin
      - /app/node_modules
    working_dir: /app
    networks:
      - silverlining

networks:
  silverlining:
    external: true
