services:
  skylynx-express:
    stdin_open: true
    tty: true
    init: true
    image: skylynx-sever
    build:
      context: .                  
      dockerfile: Dockerfile.dev
    container_name: skylynx-express-dev
    ports:
      - "5001:3200"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - silverlining

networks:
  silverlining:
    external: true
